from __future__ import annotations

from typing import ClassVar

class PvRecorder:
    frame_length: int
    sample_rate: int

    def __init__(self, device_index: int = ..., frame_length: int = ...) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def delete(self) -> None: ...
    def read(self) -> list[int]: ...
    @staticmethod
    def get_audio_devices() -> list[str]: ...
    @staticmethod
    def get_available_devices() -> list[str]: ...
