from __future__ import annotations

from pathlib import Path
from typing import Sequence

class AudioSegment:
    frame_rate: int
    channels: int
    sample_width: int
    rms: int
    max: int
    max_possible_amplitude: float

    def __init__(
        self,
        data: bytes = b"",
        *,
        sample_width: int = ...,
        frame_rate: int = ...,
        channels: int = ...,
    ) -> None: ...
    @staticmethod
    def from_mp3(file: str | Path) -> AudioSegment: ...
    @staticmethod
    def from_file(file: str | Path) -> AudioSegment: ...
    @staticmethod
    def silent(*, duration: int) -> AudioSegment: ...
    def set_frame_rate(self, frame_rate: int) -> AudioSegment: ...
    def set_channels(self, channels: int) -> AudioSegment: ...
    def apply_gain(self, volume_change: float) -> AudioSegment: ...
    def overlay(self, seg: AudioSegment, *, position: int = ...) -> AudioSegment: ...
    def speedup(self, *, playback_speed: float) -> AudioSegment: ...
    def get_array_of_samples(self) -> Sequence[int]: ...
    def export(self, out_f: str | Path, format: str) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: slice) -> AudioSegment: ...
    def __mul__(self, other: int) -> AudioSegment: ...
    def __add__(self, other: AudioSegment) -> AudioSegment: ...
    def __sub__(self, other: float) -> AudioSegment: ...
