"""Canonical retained English pronunciation expansions, with no runtime imports.

Shared by the speech formatter and customer-only pronunciation disambiguation.
Keep data in one place so customer phrase coverage cannot omit a formatter entry.
"""

from __future__ import annotations

_ACRONYM_INITIALISMS = {
    "AI": "A I",
    "API": "A P I",
    "CPU": "C P U",
    "GPU": "G P U",
    "USB": "U S B",
    "URL": "U R L",
    "FAQ": "F A Q",
    "CEO": "C E O",
    "CTO": "C T O",
    "CFO": "C F O",
    "HR": "H R",
    "NYC": "N Y C",
    "LA": "L A",
    "UK": "U K",
    "US": "U S",
    "EU": "E U",
    "UN": "U N",
    "FBI": "F B I",
    "CIA": "C I A",
    "PNG": "P N G",
    "MP3": "M P three",
    "MP4": "M P four",
    "HTML": "H T M L",
    "CSS": "C S S",
    "JS": "J S",
    "XML": "X M L",
    "PDF": "P D F",
    "DVD": "D V D",
    "GPS": "G P S",
}


_ACRONYM_WORDS = {
    "RAM": "ram",
    "ROM": "rom",
    "NATO": "nay toe",
    "NASA": "nassa",
    "JPEG": "jay peg",
    "GIF": "giff",
    "JSON": "jay sawn",
    "Wi-Fi": "why fie",
    "WiFi": "why fie",
}


_BRAND_PRONUNCIATIONS = {
    "Spotify": "Spot if eye",
    "YouTube": "you tube",
    "Anthropic": "Ann throw pick",
    "GitHub": "git hub",
    "OpenAI": "Open A I",
    "ChatGPT": "chat G P T",
    "Claude": "clawed",
    "Slack": "slack",
    "Discord": "discord",
    "Reddit": "red it",
    "Twitter": "twitter",
    "Instagram": "in stuh gram",
    "TikTok": "tick tock",
    "Netflix": "net flicks",
    "Amazon": "amazon",
    "Microsoft": "my crow soft",
    "Google": "goo gull",
    "Apple": "apple",
    "NVIDIA": "en vid ee uh",
    "AMD": "A M D",
    "Intel": "in tell",
    "Stripe": "stripe",
    "PayPal": "pay pal",
    "Venmo": "ven moe",
    "Lyft": "lift",
    "Uber": "oo ber",
    "Airbnb": "air B N B",
    "DoorDash": "door dash",
    "GrubHub": "grub hub",
    "Roku": "roh koo",
    "Sonos": "soh nohs",
    "Bose": "bohz",
    "Yamaha": "yah muh hah",
    "Wikipedia": "wick ih pee dee uh",
    "LinkedIn": "linked in",
    "Pinterest": "pin ter est",
    "Notion": "notion",
    "Figma": "fig muh",
    "Linear": "linear",
    "Asana": "uh sah nuh",
    "Trello": "trell oh",
    "Dropbox": "drop box",
    "iCloud": "eye cloud",
    "Gmail": "G mail",
    "Outlook": "out look",
}
