"""
Unified consent orchestrator for Batch B.

This service coordinates OAuth sessions across multiple providers, persists
tokens to the encrypted vault, exposes provider capability metadata, and offers
helpers for playback engines to resolve access tokens on demand.
"""

from __future__ import annotations

import threading
import uuid
from collections.abc import Iterable, Sequence
from datetime import UTC, datetime, timedelta

from core.logging_config import get_logger
from core.user_context import user_scope
from music.consent import providers
from music.consent.exceptions import (
    ConsentError,
    ProviderNotRegistered,
    TokenVaultError,
)
from music.consent.models import (
    ConsentSession,
    ConsentSessionStatus,
    ConsentStep,
    ProviderLinkState,
    ProviderStatus,
    RotationOutcome,
)
from music.consent.vault import EncryptedTokenVault

from .provider_status_manager import ProviderStatusManager
from .session_manager import ConsentSessionManager
from .token_manager import ConsentTokenManager

# Import settings manager for active provider tracking
try:
    from ui.settings_manager import get_settings_manager
except ImportError:
    # Fallback for testing environments
    def get_settings_manager():
        class MockSettingsManager:
            def get(self, key, default=None):
                return default

            def set(self, key, value, save_immediately=True):
                return True

            def get_user_setting(self, user_id, key, default=None):
                _ = user_id
                return default

            def set_user_setting(self, user_id, key, value, save_immediately=True):
                _ = (user_id, key, value, save_immediately)
                return True

        return MockSettingsManager()


from config.settings import get_runtime_base_url

logger = get_logger("viola.music.consent.service")


SESSION_TTL = timedelta(minutes=20)


def _generate_state_token() -> str:
    """Generate a random state token for OAuth CSRF protection."""
    return uuid.uuid4().hex


TOKEN_REFRESH_SKEW_SECONDS = 180
GOOGLE_CALENDAR_PROVIDER_ID = "google_calendar"

# ===================================================================
# CONSENT_FLOW_NOTES: End-to-End YouTube Music Linking Flow
# ===================================================================
#
# This documents the exact sequence for a YouTube Music linking session:
#
# 1. Start Linking Session:
#    - UI: ui/qt_native/widgets/consent_wizard.py:326 start_session()
#    - API: POST /v1/consent/session → ui/consent_api.py:54 start_session()
#    - Service: service.start_session() (line 80)
#      - Creates ConsentSession object with ConsentStep objects (one per provider)
#      - Each step has: provider_id, display_name, authorization_url, status
#      - Session stored in self._sessions dict keyed by session_id (UUID hex)
#      - Returns session with current_step_index=0 (first unlinked provider)
#
# 2. Open Authorization URL:
#    - UI: ui/qt_native/widgets/consent_wizard.py:363 open_authorization_url()
#    - Reads: self._current_step() → session.steps[current_step_index]
#    - Extracts: step.authorization_url (generated by adapter.authorization_url())
#    - Opens: webbrowser.open(authorization_url)
#    - No backend call needed (URL pre-generated and stored in session step)
#
# 3. Submit Code:
#    - UI: ui/qt_native/widgets/consent_wizard.py:457 submit_code()
#    - API: POST /v1/consent/session/{session_id}/{provider_id} with {"code": "..."}
#           → ui/consent_api.py:84 complete_step()
#    - Service: service.complete_step() (line 147)
#      a. Validates session exists and not expired
#      b. Verifies provider_id matches current step's provider_id
#      c. Gets adapter: providers.get_provider(provider_id)
#      d. Exchanges code: adapter.exchange_code(code, redirect_uri, state)
#         → music/consent/adapters/youtube_music.py:177 exchange_code()
#         → Makes HTTP POST to Google token endpoint
#         → Returns TokenBundle(access_token, refresh_token, expires_at, scopes)
#      e. Stores tokens: self._vault.store_token(provider_id, token_bundle, user_id)
#      f. Marks step: current_step.status = ProviderLinkState.LINKED
#      g. If music provider:
#         - Calls _set_active_music_provider_id(provider_id) → updates selection only
#      h. Advances: session.advance() → moves current_step_index to next provider
#      i. Returns updated session
#
# 4. UI Refresh:
#    - After submit_code(), UI calls refresh_status()
#    - API: GET /v1/consent/providers → service.list_statuses()
#    - Returns ProviderStatus objects with:
#      - state: ProviderLinkState (LINKED, NOT_LINKED, UNAVAILABLE, etc.)
#      - is_active_music_provider: bool (only True for one provider at a time)
#      - authorization_url: None (for linked providers) or URL (for unlinked)
#
# Key Objects:
# - ConsentSession: Represents a linking session (session_id, steps[], current_step_index)
# - ConsentStep: A single provider step (provider_id, authorization_url, status)
# - TokenBundle: OAuth tokens (access_token, refresh_token, expires_at)
# - ProviderLinkState: Enum (UNAVAILABLE, NOT_LINKED, PENDING, LINKED, ERROR)
#
# Connection/Selection Separation:
# - Linking a music provider stores that provider's credentials only.
# - Linking does not revoke or unlink other music providers.
# - The selected playback source is stored separately in active_music_provider_id.
#
# ===================================================================


class ConsentService:
    """Primary orchestrator for cross-provider consent flows."""

    def __init__(
        self,
        *,
        vault: EncryptedTokenVault,
        session_ttl: timedelta = SESSION_TTL,
    ) -> None:
        self._vault = vault
        self._session_ttl = session_ttl
        self._sessions: dict[str, ConsentSession] = {}
        self._state_index: dict[str, tuple[str, str]] = {}
        self._session_lock = threading.RLock()
        providers.ensure_placeholder_providers()

        # Initialize extracted managers
        self._session_manager = ConsentSessionManager(self)
        self._token_manager = ConsentTokenManager(self)
        self._status_manager = ProviderStatusManager(self)

    # ------------------------------------------------------------------#
    # Private helpers
    # ------------------------------------------------------------------#
    def _resolve_providers(
        self,
        providers_to_link: Sequence[str] | None,
        include_calendar: bool,
    ) -> list[tuple]:
        """
        Resolve requested providers to their adapters and metadata.

        Args:
            providers_to_link: List of provider IDs to include, or None for all.
            include_calendar: Whether to include calendar provider.

        Returns:
            List of (adapter, metadata) tuples for available providers.
            Each tuple contains (OAuthProviderAdapter, ProviderMetadata).
        """
        from music.consent.models import ProviderMetadata
        from music.consent.providers import OAuthProviderAdapter

        available: list[tuple[OAuthProviderAdapter, ProviderMetadata]] = []
        registered = list(providers.list_providers())

        if providers_to_link is None:
            # Include all registered providers
            for entry in registered:
                if entry.metadata.provider_id == "calendar" and not include_calendar:
                    continue
                available.append((entry.adapter, entry.metadata))
        else:
            # Include only requested providers
            for provider_id in providers_to_link:
                # get_provider returns adapter, get_metadata returns metadata
                adapter = providers.get_provider(provider_id)
                metadata = providers.get_metadata(provider_id)
                if adapter is not None and metadata is not None:
                    available.append((adapter, metadata))
                else:
                    logger.warning(
                        "Requested provider %s not registered or missing metadata",
                        provider_id,
                    )

        # Sort by display order (lower = higher priority)
        available.sort(key=lambda x: getattr(x[1], "display_order", 100))
        return available

    def _effective_user_id(self, user_id: str | None) -> str:
        """Validate that a concrete user ID was supplied."""
        if not user_id:
            raise ValueError("user_id is required")
        return user_id

    def _pop_step_state(self, state_token: str | None) -> None:
        if not state_token:
            return
        with self._session_lock:
            self._state_index.pop(state_token, None)

    @staticmethod
    def _request_includes_google_calendar(
        providers_to_link: Sequence[str] | None,
        include_calendar: bool,
    ) -> bool:
        if include_calendar:
            return True
        if providers_to_link is None:
            return False
        return any(provider_id.lower() == GOOGLE_CALENDAR_PROVIDER_ID for provider_id in providers_to_link)

    @staticmethod
    def _set_google_calendar_enabled(user_id: str, enabled: bool) -> None:
        try:
            from services.calendar.integration_state import set_google_calendar_enabled

            if not set_google_calendar_enabled(user_id, enabled):
                logger.warning(
                    "Failed to persist Google Calendar enabled=%s for user %s",
                    enabled,
                    user_id,
                )
        except Exception as exc:
            logger.warning(
                "Failed to update Google Calendar enabled=%s for user %s: %s",
                enabled,
                user_id,
                exc,
            )

    @staticmethod
    def _clear_exported_google_workspace_tokens(user_id: str) -> None:
        try:
            from services.oauth.workspace_bridge import clear_exported_workspace_tokens
        except Exception as exc:
            logger.warning(
                "Failed to load Workspace MCP credential cache cleanup for user %s: %s",
                user_id,
                exc,
            )
            raise ConsentError("Failed to clear exported Google Workspace credentials") from exc

        try:
            cleared = clear_exported_workspace_tokens()
        except Exception as exc:
            logger.warning(
                "Failed to clear Workspace MCP credential cache for user %s: %s",
                user_id,
                exc,
            )
            raise ConsentError("Failed to clear exported Google Workspace credentials") from exc
        if not cleared:
            raise ConsentError("Failed to clear exported Google Workspace credentials")

    def resolve_callback_state(self, state: str) -> dict[str, str] | None:
        """Resolve an OAuth callback state token to an active consent step."""
        with self._session_lock:
            target = self._state_index.get(state)
            if target is None:
                return None
            session_id, provider_id = target
            session = self._sessions.get(session_id)
            if (
                session is None
                or session.status != ConsentSessionStatus.ACTIVE
                or session.expires_at <= datetime.now(UTC)
            ):
                self._state_index.pop(state, None)
                return None
            return {
                "session_id": session_id,
                "provider_id": provider_id,
                "user_id": session.user_id,
            }

    def complete_step_from_state(
        self,
        state: str,
        *,
        code: str,
        redirect_uri: str | None = None,
    ) -> ConsentStep:
        resolved = self.resolve_callback_state(state)
        if resolved is None:
            raise ConsentError("No active consent step found for OAuth state")
        return self.complete_step(
            resolved["session_id"],
            provider_id=resolved["provider_id"],
            code=code,
            redirect_uri=redirect_uri,
            state=state,
        )

    def _get_active_music_provider_id(self, user_id: str) -> str | None:
        """Get the currently active music provider ID from settings."""
        settings_manager = get_settings_manager()
        return settings_manager.get_user_setting(
            user_id,
            "active_music_provider_id",
            None,
        )

    def _set_active_music_provider_id(self, user_id: str, provider_id: str | None) -> None:
        """Set the active music provider ID in settings."""
        settings_manager = get_settings_manager()
        settings_manager.set_user_setting(
            user_id,
            "active_music_provider_id",
            provider_id,
        )
        logger.info("Active music provider set to %s for user %s", provider_id, user_id)

    # ------------------------------------------------------------------#
    # Session lifecycle
    # ------------------------------------------------------------------#
    def start_session(
        self,
        *,
        user_id: str,
        providers_to_link: Sequence[str] | None = None,
        include_calendar: bool = False,
        redirect_uri: str | None = None,
    ) -> ConsentSession:
        """
        Start a new progressive consent session.

        If an active session already exists for this user, it will be reused
        (idempotent behavior) instead of creating a duplicate.
        """
        self._effective_user_id(user_id)
        if self._request_includes_google_calendar(providers_to_link, include_calendar):
            self._set_google_calendar_enabled(user_id, True)

        # Check for existing active session for this user
        with self._session_lock:
            now = datetime.now(UTC)
            existing_session = None
            for session in self._sessions.values():
                if (
                    session.user_id == user_id
                    and session.status == ConsentSessionStatus.ACTIVE
                    and session.expires_at > now
                ):
                    existing_session = session
                    break

            if existing_session is not None:
                # Mark session as reused for diagnostic logging
                existing_session._reused = True
                logger.info(
                    "Reusing existing active consent session %s for user %s (idempotent behavior)",
                    existing_session.session_id,
                    user_id,
                )
                return existing_session

        # No active session found - create a new one
        available_providers = self._resolve_providers(providers_to_link, include_calendar)

        session_id = uuid.uuid4().hex
        steps: list[ConsentStep] = []

        # Get runtime base URL for redirect URI construction
        runtime_base_url = get_runtime_base_url()
        default_redirect_uri = f"{runtime_base_url}/v1/consent/callback"

        for adapter, metadata in available_providers:
            state_token = _generate_state_token()
            try:
                # Use provided redirect_uri, metadata default, or runtime base URL
                effective_redirect_uri = redirect_uri or metadata.default_redirect_uri or default_redirect_uri
                with user_scope(user_id):
                    authorization_url = adapter.authorization_url(
                        redirect_uri=effective_redirect_uri,
                        state=state_token,
                        scopes=metadata.scopes,
                    )
                # Log expected redirect URI for this session
                if metadata.provider_id == "youtube_music":
                    logger.info(
                        "Consent redirect URI for YouTube Music session: %s",
                        effective_redirect_uri,
                    )
                status = ProviderLinkState.PENDING
                # Log when YouTube step gets authorization URL
                if metadata.provider_id == "youtube_music":
                    logger.info(
                        "YouTube Music authorization URL generated for session step "
                        "(session_id will be assigned, provider_id=youtube_music, has_url=True)"
                    )
            except Exception as exc:
                authorization_url = None
                status = ProviderLinkState.UNAVAILABLE
                # Log when YouTube step fails to generate URL
                if metadata.provider_id == "youtube_music":
                    logger.info(
                        "YouTube Music authorization URL generation failed: %s (provider_id=youtube_music, has_url=False)",
                        type(exc).__name__,
                    )

            steps.append(
                ConsentStep(
                    provider_id=metadata.provider_id,
                    display_name=metadata.display_name,
                    authorization_url=authorization_url,
                    oauth_state=state_token,
                    status=status,
                )
            )

        session = ConsentSession(
            session_id=session_id,
            user_id=user_id,
            steps=steps,
            created_at=datetime.now(UTC),
            expires_at=datetime.now(UTC) + self._session_ttl,
            redirect_uri=redirect_uri,
            include_calendar=include_calendar,
        )
        with self._session_lock:
            self._sessions[session_id] = session
            for step in steps:
                if step.oauth_state:
                    self._state_index[step.oauth_state] = (session_id, step.provider_id)
        logger.info(
            "Started new consent session %s for user %s with providers %s",
            session_id,
            user_id,
            [step.provider_id for step in steps],
        )
        return session

    def get_session(self, session_id: str) -> ConsentSession:
        return self._session_manager.get_session(session_id)

    def complete_step(
        self,
        session_id: str,
        *,
        provider_id: str,
        code: str | None = None,
        redirect_uri: str | None = None,
        state: str | None = None,
    ) -> ConsentStep:
        session = self.get_session(session_id)
        current_step = session.current_step()
        if not current_step or current_step.provider_id != provider_id:
            raise ConsentError(f"Provider '{provider_id}' is not the active step for session '{session_id}'")
        if state and current_step.oauth_state and state != current_step.oauth_state:
            raise ConsentError("OAuth state does not match the active consent step")

        adapter = providers.get_provider(provider_id)
        metadata = providers.get_metadata(provider_id)
        if adapter is None or metadata is None:
            raise ProviderNotRegistered(provider_id)

        redirect = redirect_uri or session.redirect_uri or metadata.default_redirect_uri
        if not code:
            raise ConsentError("Authorization code required to complete consent step")

        # Log when YouTube code is submitted
        if provider_id == "youtube_music":
            logger.info(
                "YouTube Music code submission started (session_id=%s, code_length=%d)",
                session_id,
                len(code) if code else 0,
            )

        try:
            token_bundle = adapter.exchange_code(code=code, redirect_uri=redirect or "", state=state)
            if provider_id == "youtube_music":
                logger.info(
                    "Disabled YouTube Music consent exchange unexpectedly succeeded (session_id=%s, has_refresh_token=%s)",
                    session_id,
                    bool(token_bundle.refresh_token),
                )
        except Exception as exc:
            current_step.status = ProviderLinkState.ERROR
            current_step.error = str(exc)
            self._pop_step_state(current_step.oauth_state)
            if provider_id == "youtube_music":
                logger.info(
                    "Disabled YouTube Music consent exchange rejected (session_id=%s, error_type=%s, error_contains_code=%s)",
                    session_id,
                    type(exc).__name__,
                    "code" in str(exc).lower() or "expired" in str(exc).lower() or "invalid" in str(exc).lower(),
                )
            raise ConsentError(f"Failed to exchange code for provider '{provider_id}': {exc}") from exc

        try:
            self._vault.store_token(
                provider_id,
                token_bundle,
                user_id=session.user_id,
                capability_metadata={"provider": provider_id},
            )
            if provider_id == "youtube_music":
                logger.info(
                    "ytm.disabled_consent: token stored unexpectedly (user_id=%s, scopes=%s, has_refresh_token=%s)",
                    session.user_id,
                    ", ".join(token_bundle.scopes) if token_bundle.scopes else "none",
                    bool(token_bundle.refresh_token),
                )
        except TokenVaultError as exc:  # pragma: no cover - defensive
            current_step.status = ProviderLinkState.ERROR
            current_step.error = str(exc)
            self._pop_step_state(current_step.oauth_state)
            raise

        # Verify tokens are actually retrievable before trusting the write
        stored = self._vault.get_token(provider_id, user_id=session.user_id)
        if not stored or not stored.refresh_token:
            current_step.status = ProviderLinkState.ERROR
            current_step.error = "Token verification failed after store"
            self._pop_step_state(current_step.oauth_state)
            raise TokenVaultError(
                f"Token verification failed for provider '{provider_id}': "
                "stored tokens are not retrievable — vault may be misconfigured"
            )

        current_step.status = ProviderLinkState.LINKED
        current_step.error = None
        self._pop_step_state(current_step.oauth_state)
        if provider_id.lower() == GOOGLE_CALENDAR_PROVIDER_ID:
            self._set_google_calendar_enabled(session.user_id, True)

        # Linking and selection are separate from other provider connections.
        # Do not revoke/unlink other music providers here; disconnect is explicit.
        if metadata.is_music_provider:
            self._set_active_music_provider_id(session.user_id, provider_id)
            logger.info(
                "Linked music provider %s for user %s via consent session %s; active music provider now: %s",
                provider_id,
                session.user_id,
                session.session_id,
                provider_id,
            )
        else:
            logger.info(
                "Linked provider %s for user %s via consent session %s",
                provider_id,
                session.user_id,
                session.session_id,
            )

        next_step = session.advance()
        if next_step:
            logger.debug(
                "Consent session %s moving to next provider %s",
                session.session_id,
                next_step.provider_id,
            )
        return current_step

    def cancel_session(self, session_id: str) -> None:
        try:
            session = self.get_session(session_id)
        except Exception:
            session = None
        if session is not None:
            for step in session.steps:
                self._pop_step_state(step.oauth_state)
        self._session_manager.cancel_session(session_id)

    # ------------------------------------------------------------------#
    # Provider orchestration
    # ------------------------------------------------------------------#
    def revoke_provider(self, user_id: str, provider_id: str) -> None:
        """
        Revoke provider access for a user.

        This method:
        1. Attempts to revoke the refresh token via the provider adapter
        2. Removes the provider record and tokens from the vault
        3. Clears active music provider if this was the active one

        Args:
            user_id: User identifier
            provider_id: Provider to revoke

        Raises:
            ProviderNotRegistered: If provider doesn't exist in registry
            ConsentError: If revocation fails
        """
        normalized_provider_id = provider_id.lower()
        adapter = providers.get_provider(normalized_provider_id)
        if adapter is None:
            raise ProviderNotRegistered(provider_id)

        # First try to revoke via adapter (best effort - don't fail if this fails)
        try:
            token_bundle = self._vault.get_token(normalized_provider_id, user_id=user_id)
            if token_bundle and token_bundle.refresh_token:
                adapter.revoke(token_bundle.refresh_token)
        except Exception as e:
            logger.warning("Failed to revoke credential via adapter for %s: %s", provider_id, e)

        if normalized_provider_id == GOOGLE_CALENDAR_PROVIDER_ID:
            self._clear_exported_google_workspace_tokens(user_id)

        # Remove tokens and record from vault
        try:
            self._vault.remove_provider(normalized_provider_id, user_id=user_id)
        except Exception as e:
            logger.warning("Failed to remove provider %s from vault: %s", provider_id, e)
            raise ConsentError("Failed to remove provider credentials for '%s'" % provider_id) from e

        # Clear active music provider if this was the active one
        metadata = providers.get_metadata(normalized_provider_id)
        if metadata and metadata.is_music_provider:
            if self._get_active_music_provider_id(user_id) == normalized_provider_id:
                settings_manager = get_settings_manager()
                settings_manager.set_user_setting(
                    user_id,
                    "active_music_provider_id",
                    None,
                )
                logger.info("Cleared active music provider (was %s)", provider_id)

        if normalized_provider_id == GOOGLE_CALENDAR_PROVIDER_ID:
            self._set_google_calendar_enabled(user_id, False)

        logger.info("Revoked provider %s for user %s", provider_id, user_id)

    def capability_matrix(self, *, user_id: str) -> dict[str, dict]:
        """
        Return capability matrix mapping provider IDs to their capabilities.

        Returns:
            Dictionary of provider_id -> capability info
        """
        matrix = {}
        for status in self.list_statuses(user_id=user_id):
            matrix[status.provider_id] = {
                "provider_id": status.provider_id,
                "capabilities": getattr(status, "capabilities", []),
                "linked": status.state == ProviderLinkState.LINKED,
                "configured": status.state != ProviderLinkState.UNAVAILABLE,
            }
        return matrix

    def list_statuses(self, user_id: str | None = None) -> Iterable[ProviderStatus]:
        """
        Return provider statuses including linked state, expiry metadata, and
        capability information.

        This method is hardened to handle per-provider errors gracefully:
        - If a provider's adapter fails, it's marked as misconfigured
        - If provider config evaluation fails, it's marked as misconfigured
        - Errors in one provider don't prevent other providers from being listed
        """
        effective_user = self._effective_user_id(user_id)
        return self._status_manager.list_statuses(effective_user)

    def resolve_access_token(self, provider_id: str, user_id: str | None = None) -> dict[str, str | int | None] | None:
        """
        Resolve access token for a provider.

        Delegates to the token manager for actual token resolution.

        Args:
            provider_id: Provider identifier
            user_id: User identifier (optional)

        Returns:
            Token data or None if not available
        """
        effective_user = self._effective_user_id(user_id)
        return self._token_manager.resolve_access_token(provider_id, effective_user)

    def rotate_tokens(
        self, *, user_id: str | None = None, min_ttl: timedelta = timedelta(hours=12)
    ) -> list[RotationOutcome]:
        """
        Rotate provider tokens when they are close to expiring.

        Args:
            user_id: User identifier (None uses the default user)
            min_ttl: Refresh tokens expiring within this time window

        Returns:
            List of rotation outcomes (one per attempted provider)
        """
        now = datetime.now(UTC)
        cutoff = now + min_ttl
        provider_ids: list[str] = []

        effective_user = self._effective_user_id(user_id)

        for status in self.list_statuses(effective_user):
            if status.state != ProviderLinkState.LINKED or status.expires_at is None:
                continue
            if status.expires_at <= cutoff:
                provider_ids.append(status.provider_id)

        if not provider_ids:
            return []

        return list(
            self._token_manager.rotate_tokens(
                user_id=effective_user,
                provider_ids=provider_ids,
                force=True,
            )
        )
